
#
# spring boot provides many options to externalize configuration.
# one option for desktop - copy this file to your home directory, update, and add
# --spring.config.location=file:c:/Users/yourHomeDir/ 


#spring.mail.host: "${mailServer:outbound.yourCompany.com}"
#spring.mail.port: "${mailPort:25}"
    
#csap-agent.host-url-pattern: "${hostUrlPattern:http://CSAP_HOST.yourCompany.com:8011/CsAgent}"

#my-service-configuration.docker.url: "tcp://localhost.yourCompany.com:4243" #"tcp://host.yourCompany.com:4243", tcp://localhost:2375, 
#my-service-configuration.docker.template-repository: "docker.io"


csap.info.load-balancer-url: "${csapLbUrl:https://csap-secure.yourCompany.com}"


test.variables:
    
    # git integration tests
    scm-userid: "changeme"
    scm-pass: "changeme"
    private-repository: "changeme" 
    private-file-validate: "changeme"
    
    # integration tests: definition
    test-external-application: "changeme"
    test-mongo-collection: "changeme"
    
    # integration tests: collection
    test-admin-host1: "changeme"
    test-admin-host2: "changeme"
    test-db-host: "changeme"
    csapUser1: "changeme"
    csapPass1: "changeme"
    
    # integration tests: CsapEvents
    user: "changeme"
    pass: "changeme"
    eventUrl: "https://csap-secure.yourcompany.com/data/api/event"
    eventApiUrl: "https://csap-secure.yourcompany.com/data/eventApi"
    eventMetricsUrl: "https://csap-secure.yourcompany.com/analytics/api/metrics/"
    analyticsUiUrl: "https://csap-secure.yourcompany.com/admin/os/performance"
    historyUiUrl: "https://csap-secure.yourcompany.com/data?appId={appId}&life={life}&category={category}&"
    
    
    # integration tests: nagios
    nagios-url: "changeme"
    nagios-token: "changeme"
    nagios-user: "changeme"
    nagios-pass: "changeme"