---
#
#  Junit tests: different profiles will force application context caching
# 
spring:
    profiles: junit
    cache:
      type: none  # cachemanager lifecycles will impact, so disable

#logging:
#  config: "classpath:a_setup/log4j2-junit.yml"
  
my-service-configuration:
  staging: target/STAGING
  processing: target/PROCESSING
        
server:
  context-path: /
  
csap:
  web-server.enabled: false
  performance.enabled: false
  security: 
    enabled: true
    ldap-enabled: true   # requires csapSecurity.properties in your home dir
  encryptable-properties:
    enabled: true
    algorithm: PBEWITHMD5ANDDES 
    property-files:
      - "csapSecurity.properties"
      - "${user.home}/csapSecurity.properties"   #overwrite the above if it exists